# Ruta base del proyecto
root = "."

# Carpetas utilizadas para tests o temporales
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Comando para compilar el binario
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp/main.exe"
  args_bin = []

  # Tiempo de espera para evitar múltiples builds por cambios rápidos
  delay = 1000

  # Directorios que NO deben observarse
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "database", ".git"]

  # Excluir archivos de test
  exclude_regex = ["_test.go"]

  # Extensiones que sí deben observarse
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Registro de errores de compilación
  log = "build-errors.log"

  # No se usa polling, solo eventos de sistema de archivos
  poll = false
  poll_interval = 0

  # Tiempo de espera antes de reiniciar
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

  # Otros flags
  exclude_file = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_file = []
  post_cmd = []
  pre_cmd = []
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true  # Limpia tmp al salir

[proxy]
  enabled = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
